baseURL = 'https://t4mag.netlify.app/'
languageCode = 'en-us'
title = 'T4 Mag'
theme = "t4mag"

[markup.goldmark.parser.attribute]
block = true
title = true

[taxonomies]
tag = "tags"
<<<<<<< HEAD
category = "categories"
=======
category = "categories"
>>>>>>> dc87bfbf74a3b6db4a26edf25793abbe2ce6a6d2
