baseURL = 'https://t4mag.netlify.app/'
languageCode = 'en-us'
title = 'T4 Mag'
theme = "t4mag"

[markup.goldmark.parser.attribute]
block = true
title = true

[taxonomies]
tag = "tags"
category = "categories"
